name: Check for News

on:
  pull_request_target:
    branches:
      - main

jobs:
  check-news-item:
    uses: Billingegroup/release-scripts/.github/workflows/_check-news-item.yml
    with:
      project: diffpy.pdfgui
